name: 🐞 Bug report
description: File a bug report
labels: [kind/bug]
title: "🐞 <title>"
body:
  - type: markdown
    attributes:
      value: |
        Please check if this bug has [already been reported](./).
  - type: textarea
    id: what-happened
    attributes:
      label: What is the issue?
      description: What happened? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: log-output
    attributes:
      label: Log output
      description: Please paste the log output
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What are the steps that we need to follow to reproduce this issue?
    validations:
      required: false
  - type: input
    id: dagger-version
    attributes:
      label: Dagger version
      description: Please paste the type + version of SDK, or the git commit number
      placeholder: e.g. NodeJS v0.3.0 | Go v0.4.0 | Python v0.2.0 | 5219a37e
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: OS version
      description: Which OS version are you running `dagger` on?
      placeholder: e.g. macOS 12.3, Ubuntu 22.04, Windows 11, etc.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        We appreciate you taking the time to report a bug.
        If you want to become a Dagger contributor and submit this improvement, everyone will appreciate it.
        You can become a contributor in less than 10 minutes. [This is how.](https://docs.dagger.io/1227/contributing#github-workflow)
