name: 📖 Documentation
description: Report a documentation issue
labels: [area/documentation]
body:
  - type: markdown
    attributes:
      value: |
        This template is strictly used for documentation requests, including:

        - Documenting undocumented APIs;
        - Elaborating on a particular topic;
        - Updating external links;
        - anything else that doesn't require code changes.

        If you followed the documentation but things don't work, was it the docs or the code?
        If the code was wrong, please file a bug report instead - link is above.

        Before you go ahead, please check if this documentation issue has [already been reported](./).
  - type: textarea
    attributes:
      label: What is the issue?
      description: A clear and concise description of what the issue is.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        We appreciate you taking the time to suggest documentation improvements.
        If you want to become a Dagger contributor and submit this improvement, we will appreciate it even more.

        [You can become a contributor in less than 10 minutes](https://github.com/dagger/.github/blob/main/CONTRIBUTING.md).
        If you try it out and it doesn't live up to this promise, we definitely want to know what would have made it better.
        All Dagger contributors will be forever grateful to you 🙌
