name: ✨ Feature request
description: Propose a new feature
title: "✨ <title>"
labels: [kind/enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Please check if this feature request has [already been filed](./).
  - type: textarea
    id: goal
    attributes:
      label: What are you trying to do?
      description: Please tell us about the goal that you are trying to achieve.
    validations:
      required: false
  - type: textarea
    id: importance
    attributes:
      label: Why is this important to you?
      description: If you think that this could be important for others, let us know.
    validations:
      required: false
  - type: textarea
    id: workaround
    attributes:
      label: How are you currently working around this?
      description: If you have a workaround in place, please share. This might help others & give us ideas.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for proposing a new feature!
