name: 🖐️ Help wanted
description: Ask for support
labels: [support]
title: "🖐️ <title>"
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? What did you expect to happen?
      description: The more detail, the better.
    validations:
      required: false
